name: Deploy to FHCOM-Server

on:
  push:
    branches:
      - master
      - main
  #schedule:
  # - cron: '0 0 * * *' # Everyday at 12am

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: npm
      - run: npm ci
      - run: npm run build

      - name: SSH deploy to server
        uses: easingthemes/ssh-deploy@v4.1.9
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.PUB_DIR }}
          SOURCE: ./dist/
