name: deploy changes

on:
  push:
    branches:
      - master
      - main
  #schedule:
   # - cron: '0 0 * * *' # Everyday at 12am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v4
      - name: Install and build site
        uses: withastro/action@v1


  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH deploy to server
        uses: easingthemes/ssh-deploy@v4.1.9
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.PUB_DIR }}
          SCRIPT_BEFORE: ls -la
